-- Service catalog: what the user sells. finding_codes/finding_categories map audit evidence to a service;
-- a trailing * in a code is a prefix wildcard (cro:* matches cro:abc). The id is the key for seeded rows.
CREATE TABLE services (
  id TEXT PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  deliverables TEXT NOT NULL DEFAULT '[]',
  prerequisites TEXT NOT NULL DEFAULT '[]',
  first_engagement TEXT,
  finding_codes TEXT NOT NULL DEFAULT '[]',
  finding_categories TEXT NOT NULL DEFAULT '[]',
  is_specialty INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0
);

INSERT INTO services (id, key, name, category, summary, finding_codes, finding_categories, is_specialty, sort) VALUES
  ('seo', 'seo', 'SEO', 'Search & Visibility', 'Improves how often and how well the business shows up in organic search results.', '["no_title_or_meta","no_h1","no_open_graph","low_seo_score","no_sitemap","thin_homepage","missing_niche_page"]', '[]', 1, 10),
  ('local-seo', 'local-seo', 'Local SEO', 'Search & Visibility', 'Builds visibility in map packs and local searches for customers near the business.', '["no_local_schema"]', '[]', 0, 20),
  ('technical-seo', 'technical-seo', 'Technical SEO', 'Search & Visibility', 'Fixes crawling, indexing, schema, and site-structure problems that hold rankings back.', '["no_schema","no_sitemap","broken_links"]', '["technical"]', 0, 30),
  ('ecommerce-seo', 'ecommerce-seo', 'Ecommerce SEO', 'Search & Visibility', 'Optimizes product and category pages so an online store earns organic traffic.', '[]', '[]', 0, 40),
  ('seo-strategy', 'seo-strategy', 'SEO Strategy', 'Search & Visibility', 'Sets the keyword, content, and priority plan for long-term organic growth.', '[]', '[]', 0, 50),
  ('ppc-paid-media', 'ppc-paid-media', 'PPC & Paid Media', 'Paid Media', 'Plans and runs paid campaigns across search, social, and display platforms.', '[]', '[]', 0, 60),
  ('paid-search', 'paid-search', 'Paid Search', 'Paid Media', 'Runs keyword-targeted ads that capture people actively searching for the service.', '[]', '[]', 0, 70),
  ('paid-social', 'paid-social', 'Paid Social', 'Paid Media', 'Runs targeted ads on social platforms to reach prospects before they search.', '[]', '[]', 0, 80),
  ('remarketing', 'remarketing', 'Remarketing', 'Paid Media', 'Re-engages past site visitors with ads until they are ready to enquire.', '[]', '[]', 0, 90),
  ('display-advertising', 'display-advertising', 'Display Advertising', 'Paid Media', 'Places banner and image ads across partner sites to build awareness.', '[]', '[]', 0, 100),
  ('social-media-marketing', 'social-media-marketing', 'Social Media Marketing', 'Paid Media', 'Manages posting and engagement on social channels to keep the brand in front of customers.', '[]', '[]', 0, 110),
  ('web-design-development', 'web-design-development', 'Web Design & Development', 'Websites', 'Designs and builds a modern, mobile-friendly website that turns visitors into enquiries.', '["not_mobile_friendly","no_viewport","mobile_overflow","small_text_mobile","dated_build","no_nav","no_footer","site_parked","no_website"]', '["design","mobile"]', 1, 120),
  ('custom-websites', 'custom-websites', 'Custom Websites', 'Websites', 'Builds a bespoke site to fit a business that outgrows templates.', '[]', '[]', 0, 130),
  ('ecommerce-websites', 'ecommerce-websites', 'Ecommerce Websites', 'Websites', 'Builds an online store with catalog, cart, and checkout.', '[]', '[]', 0, 140),
  ('wordpress-development', 'wordpress-development', 'WordPress Development', 'Websites', 'Builds and extends WordPress sites with custom themes and plugins.', '[]', '[]', 1, 150),
  ('website-accessibility', 'website-accessibility', 'Website Accessibility', 'Websites', 'Fixes barriers so people using assistive tools can use the site.', '["low_accessibility","images_missing_alt","small_text_mobile"]', '[]', 0, 160),
  ('hosting-maintenance', 'hosting-maintenance', 'Hosting & Maintenance', 'Websites', 'Keeps the site fast, secure, backed up, and updated on an ongoing plan.', '["slow_mobile","meh_mobile","slow_lcp","layout_shift","broken_links","mixed_content","no_https","no_https_redirect","no_email_auth","old_copyright","stale_content","site_unreachable"]', '["speed"]', 1, 170),
  ('branding', 'branding', 'Branding', 'Brand & Content', 'Defines how the business looks, sounds, and is remembered.', '[]', '[]', 0, 180),
  ('brand-identity', 'brand-identity', 'Brand Identity', 'Brand & Content', 'Creates the logo, colors, and type system that make the brand recognizable.', '[]', '[]', 0, 190),
  ('brand-messaging', 'brand-messaging', 'Brand Messaging', 'Brand & Content', 'Clarifies what the business says and why customers should choose it.', '[]', '[]', 0, 200),
  ('graphic-design', 'graphic-design', 'Graphic Design', 'Brand & Content', 'Produces the visuals for the website, ads, print, and social.', '[]', '[]', 1, 210),
  ('content-marketing', 'content-marketing', 'Content Marketing', 'Brand & Content', 'Publishes useful content that attracts and nurtures prospects.', '[]', '[]', 0, 220),
  ('content-strategy', 'content-strategy', 'Content Strategy', 'Brand & Content', 'Plans what to publish, for whom, and how often to support business goals.', '["stale_content","past_events","thin_homepage","old_copyright"]', '["content"]', 0, 230),
  ('copywriting', 'copywriting', 'Copywriting', 'Brand & Content', 'Writes clear, persuasive copy for pages, emails, and ads.', '[]', '[]', 0, 240),
  ('digital-marketing', 'digital-marketing', 'Digital Marketing', 'AI & Strategy', 'Combines search, social, email, and web efforts into one growth program.', '[]', '[]', 0, 250),
  ('ai-marketing', 'ai-marketing', 'AI Marketing', 'AI & Strategy', 'Uses AI tools to speed up marketing production and personalization.', '[]', '[]', 0, 260),
  ('ai-search-optimization', 'ai-search-optimization', 'AI Search Optimization', 'AI & Strategy', 'Makes the business easier for AI assistants and answer engines to find and cite.', '[]', '[]', 1, 270),
  ('generative-engine-optimization', 'generative-engine-optimization', 'Generative Engine Optimization', 'AI & Strategy', 'Shapes content so generative search engines surface and recommend the business.', '[]', '[]', 0, 280),
  ('ai-content-optimization', 'ai-content-optimization', 'AI Content Optimization', 'AI & Strategy', 'Edits and structures content so both people and AI systems can use it.', '[]', '[]', 0, 290),
  ('digital-marketing-strategy', 'digital-marketing-strategy', 'Digital Marketing Strategy', 'AI & Strategy', 'Sets goals, channels, and budget for the business''s overall marketing.', '[]', '[]', 0, 300),
  ('performance-marketing', 'performance-marketing', 'Performance Marketing', 'Growth & Optimization', 'Runs marketing against measurable outcomes such as leads and sales.', '[]', '[]', 0, 310),
  ('conversion-rate-optimization', 'conversion-rate-optimization', 'Conversion Rate Optimization', 'Growth & Optimization', 'Improves pages and calls to action so more visitors enquire or buy.', '["no_contact_path","no_cta","no_phone_visible","no_click_to_call","no_social_proof","cro:*"]', '["cro"]', 1, 320),
  ('lead-generation', 'lead-generation', 'Lead Generation', 'Growth & Optimization', 'Builds systems that bring in a steady flow of qualified enquiries.', '[]', '[]', 0, 330),
  ('analytics-attribution', 'analytics-attribution', 'Analytics & Attribution', 'Growth & Optimization', 'Sets up tracking so the business knows which efforts produce results.', '[]', '[]', 0, 340);
